version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - wordpress2
    networks:
      - cangrownet

  wordpress1:
    image: wordpress:latest
    container_name: wordpress1
    env_file:
      - ./.env
    networks:
      - cangrownet
    depends_on:
      - proxysql
    volumes:
      - wordpress_data:/var/www/html

  wordpress2:
    image: wordpress:latest
    container_name: wordpress2
    env_file:
      - ./.env
    networks:
      - cangrownet
    depends_on:
      - proxysql
    volumes:
      - wordpress_data:/var/www/html

  mariadb_master:
    image: mariadb:latest
    container_name: mariadb_master
    env_file:
      - ./.env
    volumes:
      - mariadb_master_data:/var/lib/mysql
      - ./masterdb:/opt/masterdb
      - ./masterdb/my.cnf:/etc/mysql/my.cnf
    networks:
      - cangrownet

  mariadb_replica:
    image: mariadb:latest
    container_name: mariadb_replica
    env_file:
      - ./.env
    volumes:
      - mariadb_replica_data:/var/lib/mysql
      - ./masterdb:/opt/masterdb
      - ./replicadb:/opt/replicadb
      - ./replicadb/my.cnf:/etc/mysql/my.cnf
    networks:
      - cangrownet
    depends_on:
      - mariadb_master

  proxysql:
    image: proxysql/proxysql
    container_name: proxysql
    restart: always
    volumes:
      - ./proxysql:/opt/proxysql
    depends_on:
      - mariadb_master
      - mariadb_replica
    networks:
      - cangrownet

networks:
  cangrownet:
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/28

volumes:
  mariadb_master_data:
  mariadb_replica_data:
  wordpress_data:
