version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - wordpress2
    networks:
      - cangrownet

  wordpress1:
    image: wordpress:latest
    env_file:
      - ./.env
    networks:
      - cangrownet
    depends_on:
      - mariadb_master
    volumes:
      - wordpress_data:/var/www/html

  wordpress2:
    image: wordpress:latest
    env_file:
      - ./.env
    networks:
      - cangrownet
    depends_on:
      - mariadb_master
    volumes:
      - wordpress_data:/var/www/html

  mariadb_master:
    image: mariadb:latest
    env_file:
      - ./.env
    volumes:
      - mariadb_master_data:/var/lib/mysql
      - /opt/Amirali_Salari_CanGrow/masterdb:/opt/masterdb
      - /opt/Amirali_Salari_CanGrow/masterdb/my.cnf:/etc/mysql/my.cnf
    networks:
      - cangrownet

  mariadb_replica:
    image: mariadb:latest
    env_file:
      - ./.env
    volumes:
      - mariadb_replica_data:/var/lib/mysql
    networks:
      - cangrownet
    depends_on:
      - mariadb_master

networks:
  cangrownet:

volumes:
  mariadb_master_data:
  mariadb_replica_data:
  wordpress_data:
