name: DEPLOY

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: rsync deployments
        uses: burnett01/rsync-deployments@7.0.1
        with:
          switches: -avzr --delete
          path: ./
          remote_path: /opt/Amirali_Salari_CanGrow/
          remote_host: 188.121.111.198
          remote_port: 22
          remote_user: root
          remote_key: ${{ secrets.remote_key }}
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: deploy  # This ensures that the 'build' job runs after the 'deploy' job
    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /opt/Amirali_Salari_CanGrow/
            docker compose down
            docker volume rm $(docker volume ls -q)
            docker compose up -d
            sleep 30
            docker exec -i amirali_salari_cangrow-mariadb_master-1 /bin/bash < ./masterdb/initial.sh
            docker exec -i amirali_salari_cangrow-mariadb_replica-1 /bin/bash < ./replicadb/initial.sh
            docker exec -i amirali_salari_cangrow-mariadb_master-1 /bin/bash < ./proxysql/create-monitoring-user.sh
            docker exec -i amirali_salari_cangrow-proxysql-1 /bin/bash < ./proxysql/initial.sh
